// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Bindings for `src/stow.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class StowBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  StowBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  StowBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// Initializes or opens a box with [name] in [path] (optional).
  /// Returns 0 on success, and writes the box handle to [*out_handle].
  /// Returns negative value on error.
  int stow_init_box(
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Char> path,
    ffi.Pointer<ffi.Uint64> out_handle,
  ) {
    return _stow_init_box(name, path, out_handle);
  }

  late final _stow_init_boxPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Uint64>,
          )
        >
      >('stow_init_box');
  late final _stow_init_box = _stow_init_boxPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Uint64>,
        )
      >();

  /// Synchronously reads a value by [key] from the box specified by [handle].
  /// If found, returns 1, writes pointer to [*out_val_ptr] and length to [*out_val_len].
  /// The returned buffer must be freed using [stow_free_bytes].
  /// If not found, returns 0.
  /// Returns negative value on error.
  int stow_read(
    int handle,
    ffi.Pointer<ffi.Uint8> key_ptr,
    int key_len,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_val_ptr,
    ffi.Pointer<ffi.Size> out_val_len,
  ) {
    return _stow_read(handle, key_ptr, key_len, out_val_ptr, out_val_len);
  }

  late final _stow_readPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Uint64,
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('stow_read');
  late final _stow_read = _stow_readPtr
      .asFunction<
        int Function(
          int,
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  /// Writes [val] for [key] to the box specified by [handle].
  /// Returns 0 on success, negative value on error.
  int stow_write(
    int handle,
    ffi.Pointer<ffi.Uint8> key_ptr,
    int key_len,
    ffi.Pointer<ffi.Uint8> val_ptr,
    int val_len,
  ) {
    return _stow_write(handle, key_ptr, key_len, val_ptr, val_len);
  }

  late final _stow_writePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Uint64,
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
          )
        >
      >('stow_write');
  late final _stow_write = _stow_writePtr
      .asFunction<
        int Function(
          int,
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Uint8>,
          int,
        )
      >();

  /// Removes [key] from the box specified by [handle].
  /// Returns 1 if removed, 0 if not found, negative value on error.
  int stow_remove(int handle, ffi.Pointer<ffi.Uint8> key_ptr, int key_len) {
    return _stow_remove(handle, key_ptr, key_len);
  }

  late final _stow_removePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Uint64, ffi.Pointer<ffi.Uint8>, ffi.Size)
        >
      >('stow_remove');
  late final _stow_remove = _stow_removePtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Uint8>, int)>();

  /// Checks if [key] exists in the box specified by [handle].
  /// Returns 1 if key exists, 0 if not found, negative value on error.
  int stow_contains(int handle, ffi.Pointer<ffi.Uint8> key_ptr, int key_len) {
    return _stow_contains(handle, key_ptr, key_len);
  }

  late final _stow_containsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Uint64, ffi.Pointer<ffi.Uint8>, ffi.Size)
        >
      >('stow_contains');
  late final _stow_contains = _stow_containsPtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Uint8>, int)>();

  /// Returns the number of keys in the box specified by [handle].
  /// Returns negative value on error.
  int stow_keys_count(int handle) {
    return _stow_keys_count(handle);
  }

  late final _stow_keys_countPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function(ffi.Uint64)>>(
        'stow_keys_count',
      );
  late final _stow_keys_count = _stow_keys_countPtr
      .asFunction<int Function(int)>();

  /// Returns all keys in the box as packed bytes: count(u32), [len(u32), bytes]*
  /// The returned buffer must be freed using [stow_free_bytes].
  int stow_get_all_keys(
    int handle,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_keys_ptr,
    ffi.Pointer<ffi.Size> out_keys_len,
  ) {
    return _stow_get_all_keys(handle, out_keys_ptr, out_keys_len);
  }

  late final _stow_get_all_keysPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Uint64,
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('stow_get_all_keys');
  late final _stow_get_all_keys = _stow_get_all_keysPtr
      .asFunction<
        int Function(
          int,
          ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  /// Clears all keys from the box specified by [handle].
  /// Returns 0 on success, negative value on error.
  int stow_clear(int handle) {
    return _stow_clear(handle);
  }

  late final _stow_clearPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Uint64)>>('stow_clear');
  late final _stow_clear = _stow_clearPtr.asFunction<int Function(int)>();

  /// Compacts the database file to remove deleted/overwritten entries.
  /// Returns 0 on success, negative value on error.
  int stow_compact(int handle) {
    return _stow_compact(handle);
  }

  late final _stow_compactPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Uint64)>>(
        'stow_compact',
      );
  late final _stow_compact = _stow_compactPtr.asFunction<int Function(int)>();

  /// Closes the box specified by [handle].
  /// Returns 0 on success, negative value on error.
  int stow_close(int handle) {
    return _stow_close(handle);
  }

  late final _stow_closePtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Uint64)>>('stow_close');
  late final _stow_close = _stow_closePtr.asFunction<int Function(int)>();

  /// Frees a byte buffer allocated by stow.
  void stow_free_bytes(ffi.Pointer<ffi.Uint8> ptr, int len) {
    return _stow_free_bytes(ptr, len);
  }

  late final _stow_free_bytesPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Uint8>, ffi.Size)>
      >('stow_free_bytes');
  late final _stow_free_bytes = _stow_free_bytesPtr
      .asFunction<void Function(ffi.Pointer<ffi.Uint8>, int)>();

  /// Frees a string allocated by stow.
  void stow_free_string(ffi.Pointer<ffi.Char> ptr) {
    return _stow_free_string(ptr);
  }

  late final _stow_free_stringPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
        'stow_free_string',
      );
  late final _stow_free_string = _stow_free_stringPtr
      .asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  /// Gets the last error message, if any.
  /// The returned string must be freed using [stow_free_string].
  int stow_last_error(ffi.Pointer<ffi.Pointer<ffi.Char>> out_ptr) {
    return _stow_last_error(out_ptr);
  }

  late final _stow_last_errorPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<ffi.Pointer<ffi.Char>>)
        >
      >('stow_last_error');
  late final _stow_last_error = _stow_last_errorPtr
      .asFunction<int Function(ffi.Pointer<ffi.Pointer<ffi.Char>>)>();
}

// ---------------------------------------------------------------------------
// Native Asset Bindings (Zero-overhead direct link via build hook)
// ---------------------------------------------------------------------------

@ffi.Native<ffi.Int32 Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Uint64>)>(symbol: 'stow_init_box')
external int nativeStowInitBox(
  ffi.Pointer<ffi.Char> name,
  ffi.Pointer<ffi.Char> path,
  ffi.Pointer<ffi.Uint64> out_handle,
);

@ffi.Native<ffi.Int32 Function(ffi.Uint64, ffi.Pointer<ffi.Uint8>, ffi.Size, ffi.Pointer<ffi.Pointer<ffi.Uint8>>, ffi.Pointer<ffi.Size>)>(symbol: 'stow_read')
external int nativeStowRead(
  int handle,
  ffi.Pointer<ffi.Uint8> key_ptr,
  int key_len,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_val_ptr,
  ffi.Pointer<ffi.Size> out_val_len,
);

@ffi.Native<ffi.Int32 Function(ffi.Uint64, ffi.Pointer<ffi.Uint8>, ffi.Size, ffi.Pointer<ffi.Uint8>, ffi.Size)>(symbol: 'stow_write')
external int nativeStowWrite(
  int handle,
  ffi.Pointer<ffi.Uint8> key_ptr,
  int key_len,
  ffi.Pointer<ffi.Uint8> val_ptr,
  int val_len,
);

@ffi.Native<ffi.Int32 Function(ffi.Uint64, ffi.Pointer<ffi.Uint8>, ffi.Size)>(symbol: 'stow_remove')
external int nativeStowRemove(
  int handle,
  ffi.Pointer<ffi.Uint8> key_ptr,
  int key_len,
);

@ffi.Native<ffi.Int32 Function(ffi.Uint64, ffi.Pointer<ffi.Uint8>, ffi.Size)>(symbol: 'stow_contains')
external int nativeStowContains(
  int handle,
  ffi.Pointer<ffi.Uint8> key_ptr,
  int key_len,
);

@ffi.Native<ffi.Int64 Function(ffi.Uint64)>(symbol: 'stow_keys_count')
external int nativeStowKeysCount(int handle);

@ffi.Native<ffi.Int32 Function(ffi.Uint64, ffi.Pointer<ffi.Pointer<ffi.Uint8>>, ffi.Pointer<ffi.Size>)>(symbol: 'stow_get_all_keys')
external int nativeStowGetAllKeys(
  int handle,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_keys_ptr,
  ffi.Pointer<ffi.Size> out_keys_len,
);

@ffi.Native<ffi.Int32 Function(ffi.Uint64)>(symbol: 'stow_clear')
external int nativeStowClear(int handle);

@ffi.Native<ffi.Int32 Function(ffi.Uint64)>(symbol: 'stow_compact')
external int nativeStowCompact(int handle);

@ffi.Native<ffi.Int32 Function(ffi.Uint64)>(symbol: 'stow_close')
external int nativeStowClose(int handle);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Uint8>, ffi.Size)>(symbol: 'stow_free_bytes')
external void nativeStowFreeBytes(ffi.Pointer<ffi.Uint8> ptr, int len);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char>)>(symbol: 'stow_free_string')
external void nativeStowFreeString(ffi.Pointer<ffi.Char> ptr);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<ffi.Pointer<ffi.Char>>)>(symbol: 'stow_last_error')
external int nativeStowLastError(ffi.Pointer<ffi.Pointer<ffi.Char>> out_ptr);

